name: Package

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  package:
    uses: normlanguage/registry/.github/workflows/package.yml@c42fcb813fd549d179896d358eb774543a9b6c0d
    with:
      norm-source-ref: 9dd8571427f77e7fa9b9adab38ac1272f7d82d2a
      runner: windows-2025
